#!/usr/bin/env python3
import rospy
from migrave_behaviour_manager_wrapper.behaviour_manager_wrapper import BehaviourManagerWrapper

if __name__ == '__main__':
    rospy.init_node('behaviour_manager')
    behaviour_manager = BehaviourManagerWrapper()
    try:
        while not rospy.is_shutdown():
            behaviour_manager.act()
            rospy.sleep(0.05)
    except rospy.ROSInterruptException as exc:
        print('behaviour_manager exiting...')
