#!/usr/bin/env python3
import rospy

from migrave_behaviour_manager.action_interface import ActionInterface
from migrave_behaviour_manager.behaviour_manager import RobotBehaviourManager
from migrave_ros_msgs.msg import RobotAction, AffectiveState

class BehaviourManagerNode(object):
    def __init__(self):
        action_config_path = rospy.get_param('~action_config_path', '')
        action_topic = rospy.get_param('~action_topic', '/robot_action')
        affective_state_topic = rospy.get_param('~affective_state_topic', '/affective_state')

        self.current_affective_state = None
        self.robot_action_msg = RobotAction()
        self.action_interface = ActionInterface(action_config_path)
        self.behaviour_manager = RobotBehaviourManager()

        self.action_pub = rospy.Publisher(action_topic, RobotAction, queue_size=1)
        self.state_sub = rospy.Subscriber(affective_state_topic,
                                          AffectiveState,
                                          self.affective_state_cb)

    def act(self) -> None:
        """Retrieves an appropriate action for the robot and
        publishes it to an action executor.
        """
        action_name = self.behaviour_manager.get_action(None)
        action_params = self.action_interface.get_action(action_name)

        self.robot_action_msg.action_id = action_params['id']
        self.robot_action_msg.action_name = action_params['name']
        self.robot_action_msg.sentence = action_params['sentence']
        self.robot_action_msg.gesture_type = action_params['gesture']
        self.robot_action_msg.face_expression = action_params['face_expression']
        self.robot_action_msg.stamp = rospy.Time.now()

        self.action_pub.publish(self.robot_action_msg)

    def affective_state_cb(self, affective_state_msg: AffectiveState) -> None:
        self.current_affective_state = affective_state_msg

if __name__ == '__main__':
    rospy.init_node('behaviour_manager')
    behaviour_manager = BehaviourManagerNode()
    try:
        while not rospy.is_shutdown():
            behaviour_manager.act()
            rospy.sleep(0.05)
    except rospy.ROSInterruptException as exc:
        print('behaviour_manager exiting...')
