- id: do_nothing
  name: Do nothing
  sentence: ''
  gesture: none
  face_expression: none

- id: self_introduce
  name: Self-introduce
  sentence: Hallo Ich bin QT Robot!
  gesture: send_kiss
  face_expression: happy

- id: give_feedback
  name: Give feedback
  sentence: Gut gemacht, weiter so
  gesture: clapping
  face_expression: happy

- id: come_back
  name: Come back
  sentence: Wo bist du? Komm zurueck!
  gesture: one-arm-up
  face_expression: sad

- id: relax_child
  name: Relax child
  sentence: Wieso bist du wuetend? Sieh mich an!
  gesture: neutral
  face_expression: calm