- id: do_nothing
  name: Do nothing
  sentence: ''
  gesture: none
  face_expression: none

- id: self_introduce
  name: Self-introduce
  sentence: Hello I am QT robot
  gesture: send_kiss
  face_expression: happy

- id: give_feedback
  name: Give feedback
  sentence: Very good, keep going
  gesture: clapping
  face_expression: happy

- id: come_back
  name: Come back
  sentence: Please come back, I am sad
  gesture: one-arm-up
  face_expression: sad

- id: relax_child
  name: Relax child
  sentence: You are quite nervous, lets relax
  gesture: neutral
  face_expression: calm