game_id: animals
general_game_params:
    tasks: [cat, cat_vs_objects, cat_vs_animals, dog, dog_vs_objects, dog_vs_animals,
            cow, cow_vs_objects, cow_vs_animals, pig, pig_vs_objects, pig_vs_animals,
            mouse, mouse_vs_objects, mouse_vs_animals, animal_vs_objects, animal_vs_animals]
    resumption_tasks: [animal_vs_objects_resume, animal_vs_animals_resume]
    game_activity_ids:
        cat: cat
        cow: cow
        pig: pig
        dog: dog
        mouse: mouse

        cat_vs_objects: cat_vs_objects
        cow_vs_objects: cow_vs_objects
        pig_vs_objects: pig_vs_objects
        dog_vs_objects: dog_vs_objects
        mouse_vs_objects: dog_vs_objects
        
        cat_vs_animals: cat_vs_animals
        cow_vs_animals: cow_vs_animals
        pig_vs_animals: pig_vs_animals
        dog_vs_animals: dog_vs_animals
        mouse_vs_animals: dog_vs_animals

        animal_vs_objects: animal_vs_objects
        animal_vs_animals: animal_vs_animals

        animal_vs_objects_resume: animal_vs_objects_resume
        animal_vs_animals_resume: animal_vs_animals_resume

    difficulty_levels:
        cat: 1
        cow: 1
        pig: 1
        dog: 1
        mouse: 1
        cat_vs_objects: 1
        cow_vs_objects: 1
        pig_vs_objects: 1
        dog_vs_objects: 1
        mouse_vs_objects: 1
        cat_vs_animals: 2
        cow_vs_animals: 2
        pig_vs_animals: 2
        dog_vs_animals: 2
        mouse_vs_animals: 2
        animal_vs_objects: 3
        animal_vs_animals: 4

    end_sentence: Geschafft, wir sind fertig für heute. Gut gemacht!
game_specific_params:
    options: [cat, dog, cow, pig, mouse] 
    target_animals: 
        cat: [cat-1, cat-2, cat-3]
        dog: [dog-1, dog-2, dog-3]
        cow: [cow-1, cow-2, cow-3]
        pig: [pig-1, pig-2, pig-3]
        mouse: [mouse-1, mouse-2]
    distractor_objects: [backpack, hammer, chair, shovel, scissors, shoes, bucket, pencil, pot, brick]
    distractor_animals: [giraffe, sheep, duck, chicken, elephant, rabbit, guinea_pig, horse, donkey, peacock]
    generalisation_objects:
        cat: [cat-cartoon-1, cat-cartoon-2, cat-cartoon-3]
        dog: [dog-cartoon-1, dog-cartoon-2, dog-cartoon-3]
        cow: [cow-cartoon-1, cow-cartoon-2, cow-cartoon-3]
        pig: [pig-cartoon-1, pig-cartoon-2, pig-cartoon-3]
        mouse: [mouse-cartoon-1, mouse-cartoon-2, mouse-cartoon-3]
    # media_params:
    #     celebration_sound_name: rfh-koeln/MIGRAVE/Fireworks

