game_id: animals
general_game_params:
    tasks: [cat, cat_vs_objects, cat_vs_animals, cat_vs_others,
            dog, dog_vs_objects, dog_vs_animals, dog_vs_others,
            cow, cow_vs_objects, cow_vs_animals, cow_vs_others,
            horse, horse_vs_objects, horse_vs_animals, horse_vs_others, 
            cartoon_vs_objects, black-white_vs_objects, draw_vs_objects, animal_vs_animals
            ]
    resumption_tasks: [cat_resume, dog_resume, cow_resume, horse_resume]
    game_activity_ids:
        cat: cat
        cow: cow
        horse: horse
        dog: dog
        cat_vs_objects: cat_vs_objects
        cow_vs_objects: cow_vs_objects
        horse_vs_objects: horse_vs_objects
        dog_vs_objects: dog_vs_objects
        cat_vs_animals: cat_vs_animals
        cow_vs_animals: cow_vs_animals
        horse_vs_animals: horse_vs_animals
        dog_vs_animals: dog_vs_animals
        cat_vs_others: cat_vs_others
        cow_vs_others: cow_vs_others
        horse_vs_others: horse_vs_others
        dog_vs_others: dog_vs_others
        cartoon_vs_objects: cartoon_vs_objects
        black-white_vs_objects: black-white_vs_objects
        draw_vs_objects: draw_vs_objects
        animal_vs_animals: animal_vs_animals
        cat_resume: cat
        cow_resume: cow
        horse_resume: horse
        dog_resume: dog
        cartoon_vs_objects_resume: cartoon_vs_objects_resume
        black-white_vs_objects_resume: black-white_vs_objects_resume
        draw_vs_objects_resume: draw_vs_objects_resume
        animal_vs_animals_resume: animal_vs_animals_resume
    difficulty_levels:
        cat: 1
        cow: 1
        horse: 1
        dog: 1
        cat_vs_objects: 2
        cow_vs_objects: 2
        horse_vs_objects: 2
        dog_vs_objects: 2
        cat_vs_animals: 3
        cow_vs_animals: 3
        horse_vs_animals: 3
        dog_vs_animals: 3
        cat_vs_others: 4
        cow_vs_others: 4
        horse_vs_others: 4
        dog_vs_others: 4
        cartoon_vs_objects: 5
        black-white_vs_objects: 5 
        draw_vs_objects: 5
        animal_vs_animals: 5
    end_sentence: Wir sind fertig mit Farben lernen. Gut gemacht!
game_specific_params:
    target_animals: [cat, dog, cow, horse]
    distractor_objects: [ball, bike, bottle, oranges, truck, watermelon, sun, shell]
    distractor_animals: [rabbit, cricket, bird, alpaca, lion, fish, rooster, gorilla]
    generalisation_objects:
        cat: [cat-cartoon, cat-black-white, cat-draw]
        dog: [dog-cartoon, dog-black-white, dog-draw]
        cow: [cow-cartoon, cow-black-white, cow-draw]
        horse: [horse-cartoon, horse-black-white, horse-draw]
media_params:
    celebration_sound_name: rfh-koeln/MIGRAVE/Fireworks
    cat_sound_name: aleksandar.mitrevski/animals/cat
    dog_sound_name: aleksandar.mitrevski/animals/dog
    cow_sound_name: aleksandar.mitrevski/animals/cow
    horse_sound_name: aleksandar.mitrevski/animals/horse