game_id: colors
general_game_params:
    tasks: [red, red_vs_other, yellow, yellow_vs_other, red_or_yellow_vs_other,
            blue, blue_vs_other, green, green_vs_other, blue_or_green_vs_other,
            three_squares, three_cars, three_objects]
    resumption_tasks: [red_resume, yellow_resume, blue_resume, green_resume]
    game_activity_ids:
        red: red
        blue: blue
        green: green
        yellow: yellow
        red_vs_other: red_vs_other
        blue_vs_other: blue_vs_other
        green_vs_other: green_vs_other
        yellow_vs_other: yellow_vs_other
        red_or_yellow_vs_other: red_or_yellow_vs_other
        blue_or_green_vs_other: blue_or_green_vs_other
        three_squares: three_squares
        three_cars: three_cars
        three_objects: three_objects
        red_resume: red
        blue_resume: blue
        green_resume: green
        yellow_resume: yellow
    difficulty_levels:
        red: 1
        blue: 1
        green: 1
        yellow: 1
        red_vs_other: 2
        blue_vs_other: 2
        green_vs_other: 2
        yellow_vs_other: 2
        red_or_yellow_vs_other: 3
        blue_or_green_vs_other: 3
        three_squares: 4
        three_cars: 4
        three_objects: 5
    end_sentence: Wir sind fertig mit Farben lernen. Gut gemacht!
game_specific_params:
    target_colors: [red, yellow, blue, green]
    distractor_colors: [black, brown, lilac, orange, pink]
    generalisation_objects:
        red: [red-car, red-ball, red-bike, red-flower, red-socks, red-strawberry, red-toys, red-t-shirt, red-watering-can]
        yellow: [yellow-car, yellow-ball, yellow-bike, yellow-flower, yellow-socks, yellow-banana, yellow-toys, yellow-t-shirt, yellow-watering-can]
        blue: [blue-car, blue-ball, blue-bike, blue-flower, blue-socks, blue-blueberries, blue-toys, blue-t-shirt, blue-watering-can]
        green: [green-car, green-ball, green-bike, green-flower, green-socks, green-apple, green-toys, green-t-shirt, green-watering-can]
media_params:
    celebration_sound_name: rfh-koeln/MIGRAVE/Fireworks
