game_id: tableware
general_game_params:
    tasks: [fork, fork_vs_objects, spoon, spoon_vs_objects, knife, knife_vs_objects, glass, 
            glass_vs_objects, bowl, bowl_vs_objects, fork_vs_tableware, spoon_vs_tableware, 
            knife_vs_tableware, glass_vs_tableware, bowl_vs_tableware, object_vs_others, kid_vs_kids, object_vs_random]
    resumption_tasks: [fork_resume, spoon_resume, knife_resume, glass_resume, bowl_resume,   
                       object_vs_others_resume, kid_vs_kids_resume, object_vs_random_resume]
    game_activity_ids:
        fork: fork
        spoon: spoon
        knife: knife
        glass: glass 
        bowl: bowl

        fork_vs_objects: fork_vs_objects
        spoon_vs_objects: spoon_vs_objects
        knife_vs_objects: knife_vs_objects
        glass_vs_objects: glass_vs_objects
        bowl_vs_objects: bowl_vs_objects

        fork_vs_tableware: fork_vs_tableware
        spoon_vs_tableware: spoon_vs_tableware
        knife_vs_tableware: knife_vs_tableware
        glass_vs_tableware: glass_vs_tableware 
        bowl_vs_tableware: bowl_vs_tableware

        object_vs_others: object_vs_others
        kid_vs_kids: kid_vs_kids
        object_vs_random: object_vs_random

        fork_resume: fork
        teacup_resume: teacup
        spoon_resume: spoon
        plate_resume: plate

        object_vs_others_resume: object_vs_others_resume
        kid_vs_kids_resume: kid_vs_kids_resume
        object_vs_random_resume: object_vs_random_resume
          
    difficulty_levels:
        fork: 1
        spoon: 1
        knife: 1
        glass: 1 
        bowl: 1
        fork_vs_objects: 1
        spoon_vs_objects: 1
        knife_vs_objects: 1
        glass_vs_objects: 1
        bowl_vs_objects: 1
        fork_vs_tableware: 2
        spoon_vs_tableware: 2
        knife_vs_tableware: 2
        glass_vs_tableware: 2 
        bowl_vs_tableware: 2
        object_vs_others: 3
        kid_vs_kids: 4
        object_vs_random: 5

    end_sentence: Wir sind fertig für heute. Gut gemacht! 
game_specific_params:
    options: [fork, spoon, knife, glass, bowl]
    target_tableware: 
        fork: [fork-1, fork-2, fork-3, fork-4, fork-5]
        spoon: [spoon-1, spoon-2, spoon-3, spoon-4, spoon-5]
        knife: [knife-1, knife-2, knife-3, knife-4, knife-5]
        glass: [glass-1, glass-2, glass-3, glass-4, glass-5]
        bowl: [bowl-1, bowl-2, bowl-3, bowl-4, bowl-5]
    distractor_objects: [backpack, hammer, chair, shovel, scissors, shoes, bucket, pencil, pot, brick]
    generalisation_objects: [fork-kid, spoon-kid, knife-kid, glass-kid, bowl-kid]
media_params:
    celebration_sound_name: rfh-koeln/MIGRAVE/Fireworks
